#index:
#    path: /
#    controller: App\Controller\DefaultController::index

rabbitmq-test:
    path: /rabbitmq-test
    controller: App\Controller\TestController::rabbitmqTest

queues:
    type: rest
    resource: App\Controller\RabbitmqController