# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
fos_rest:
  zone:
    - { path: ^/api/* }
  disable_csrf_role: ROLE_ADMIN
  allowed_methods_listener: true
  param_fetcher_listener: true
  body_listener: true
  format_listener:
    enabled: true
    rules:
      - { path: '^/api', priorities: ['json'], fallback_format: 'json' }
  versioning: true
  view:
    view_response_listener: true
  routing_loader:
    default_format: json