old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        playground:
            connection:       default
            exchange_options: { name: 'ppm-parse', type: direct }
    consumers:
        playground:
            connection:       default
            exchange_options: { name: 'ppm-parse', type: direct }
            queue_options:    { name: 'ppm-parse'}
            callback:         App\Consumer\PlaygroundConsumer
